const SensorTypeLabels = {
  BeaconTracking: "BeaconTracking",
  Boolean: "Boolean",
  CargoContainerISOReader: "CargoContainerISOReader",
  Checkout: "Checkout",
  ColorPresence: "ColorPresence",
  ConcentrationAlert: "ConcentrationAlert",
  CrossLineMultiRecognition: "CrossLineMultiRecognition",
  CrossLineRecognition: "CrossLineRecognition",
  CrossedBarriersDetection: "CrossedBarriersDetection",
  Debug: "Debug",
  FaceDetection: "FaceDetection",
  FaceMaskDetection: "FaceMaskDetection",
  FaceRecognition: "FaceRecognition",
  FuelingDetection: "FuelingDetection",
  GPS: "GPS",
  GranularityDetection: "GranularityDetection",
  Heatmap: "Heatmap",
  LicensePlate: "LicensePlate",
  LicensePlateText: "LicensePlateText",
  LineCrossingDetection: "LineCrossingDetection",
  MissingHelmetDetection: "MissingHelmetDetection",
  MotionDetection: "MotionDetection",
  MultiLineCrossingDetection: "MultiLineCrossingDetection",
  MultiZoneObjectTracking: "MultiZoneObjectTracking",
  NaiveSocialDistancing: "NaiveSocialDistancing",
  NoPlateDetection: "NoPlateDetection",
  Number: "Number",
  ObjectCounting: "ObjectCounting",
  ObjectRecognition: "ObjectRecognition",
  ObjectRecognitionNumeric: "ObjectRecognitionNumeric",
  OpeningDetection: "OpeningDetection",
  OpticalCharacterRecognition: "OpticalCharacterRecognition",
  OverlapDetection: "OverlapDetection",
  PanicButton: "PanicButton",
  PeriodicObjectCounting: "PeriodicObjectCounting",
  PoseDetection: "PoseDetection",
  QueueSize: "QueueSize",
  Referrer: "Referrer",
  SceneChange: "SceneChange",
  ShoppingHours: "ShoppingHours",
  SpeedChange: "SpeedChange",
  StoppedLicensePlate: "StoppedLicensePlate",
  StoppedObjectsDetector: "StoppedObjectsDetector",
  String: "String",
  Video: "Video",
} as const;

export type SensorTypeLabels = typeof SensorTypeLabels;
export type SensorTypeLabel = SensorTypeLabels[keyof SensorTypeLabels];
