const _SensorTypeLabels = {
  BeaconTracking: 'BeaconTracking',
  Boolean: 'Boolean',
  Checkout: 'Checkout',
  ColorPresence: 'ColorPresence',
  ConcentrationAlert: 'ConcentrationAlert',
  CrossedBarriersDetection: 'CrossedBarriersDetection',
  CrossLineMultiRecognition: 'CrossLineMultiRecognition',
  CrossLineRecognition: 'CrossLineRecognition',
  Debug: 'Debug',
  FaceDetection: 'FaceDetection',
  FaceMaskDetection: 'FaceMaskDetection',
  FuelingDetection: 'FuelingDetection',
  GPS: 'GPS',
  LicensePlate: 'LicensePlate',
  LicensePlateText: 'LicensePlateText',
  LineCrossingDetection: 'LineCrossingDetection',
  MotionDetection: 'MotionDetection',
  NaiveSocialDistancing: 'NaiveSocialDistancing',
  NoPlateDetection: 'NoPlateDetection',
  Number: 'Number',
  ObjectCounting: 'ObjectCounting',
  ObjectRecognition: 'ObjectRecognition',
  OpeningDetection: 'OpeningDetection',
  OpticalCharacterRecognition: 'OpticalCharacterRecognition',
  PoseDetection: 'PoseDetection',
  QueueSize: 'QueueSize',
  Referrer: 'Referrer',
  SceneChange: 'SceneChange',
  ShoppingHours: 'ShoppingHours',
  SpeedChange: 'SpeedChange',
  StoppedLicensePlate: 'StoppedLicensePlate',
  StoppedObjectsDetector: 'StoppedObjectsDetector',
  String: 'String',
  Video: 'Video',
} as const;

export type SensorTypeLabels = typeof _SensorTypeLabels;
type SensorTypeKey = keyof typeof _SensorTypeLabels;
export type SensorTypeLabel = (typeof _SensorTypeLabels)[SensorTypeKey];
