const _YoloClassLabels = {
  AEROPLANE: 'aeroplane',
  APPAREL: 'apparel',
  APPLE: 'apple',
  BACKPACK: 'backpack',
  BAG: 'bag',
  BANANA: 'banana',
  BARRIER: 'barrier',
  BASEBALL_BAT: 'baseball bat',
  BASEBALL_GLOVE: 'baseball glove',
  BEAR: 'bear',
  BED: 'bed',
  BENCH: 'bench',
  BICYCLE: 'bicycle',
  BIRD: 'bird',
  BOAT: 'boat',
  BOOK: 'book',
  BOTTLE: 'bottle',
  BOWL: 'bowl',
  BOX: 'box',
  BROCCOLI: 'broccoli',
  BULLDOZER: 'bulldozer',
  BUS: 'bus',
  CAKE: 'cake',
  CAR: 'car',
  CARROT: 'carrot',
  CAT: 'cat',
  CELL_PHONE: 'cell phone',
  CELLPHONE: 'cellphone',
  CHAIR: 'chair',
  CLOCK: 'clock',
  CONE: 'cone',
  COW: 'cow',
  CUP: 'cup',
  DELIVERYBAG: 'deliverybag',
  DININGTABLE: 'diningtable',
  DOCUMENT: 'document',
  DOG: 'dog',
  DONUT: 'donut',
  ELEPHANT: 'elephant',
  EQUIPMENT: 'equipment',
  EXCAVATOR: 'excavator',
  FIRE_HYDRANT: 'fire hydrant',
  FIREHYDRANT: 'firehydrant',
  FLATBED_TRAILER: 'flatbed-trailer',
  FORK: 'fork',
  FORKLIFT: 'forklift',
  FRISBEE: 'frisbee',
  GIRAFFE: 'giraffe',
  GUARD: 'guard',
  HAIR_DRIER: 'hair drier',
  HANDBAG: 'handbag',
  HEAD: 'head',
  HELMET: 'helmet',
  HORSE: 'horse',
  HOT_DOG: 'hot dog',
  INSPECTOR: 'inspector',
  KEYBOARD: 'keyboard',
  KITE: 'kite',
  KNIFE: 'knife',
  LABEL: 'label',
  LAPTOP: 'laptop',
  LICENSE_PLATE: 'license_plate',
  MACHINERY: 'machinery',
  MANIKI: 'maniki',
  MICROWAVE: 'microwave',
  MOTORBIKE: 'motorbike',
  MOUSE: 'mouse',
  ORANGE: 'orange',
  OVEN: 'oven',
  PARKING_METER: 'parking meter',
  PERSON: 'person',
  PET: 'pet',
  PISTOL: 'pistol',
  PIZZA: 'pizza',
  POTTEDPLANT: 'pottedplant',
  REFRIGERATOR: 'refrigerator',
  REMOTE: 'remote',
  SANDWICH: 'sandwich',
  SCISSORS: 'scissors',
  SCOOTER: 'scooter',
  SHEEP: 'sheep',
  SHOEBOX: 'shoebox',
  SINK: 'sink',
  SKATEBOARD: 'skateboard',
  SKIS: 'skis',
  SNEAKERS: 'sneakers',
  SNOWBOARD: 'snowboard',
  SOCKS: 'socks',
  SOFA: 'sofa',
  SPOON: 'spoon',
  SPORTS_BALL: 'sports ball',
  STOP_SIGN: 'stop sign',
  SUITCASE: 'suitcase',
  SURFBOARD: 'surfboard',
  TEDDY_BEAR: 'teddy bear',
  TENNIS_RACKET: 'tennis racket',
  TIE: 'tie',
  TOASTER: 'toaster',
  TOILET: 'toilet',
  TOOTHBRUSH: 'toothbrush',
  TRAFFIC_LIGHT: 'traffic light',
  TRAIN: 'train',
  TRASHBIN: 'trashbin',
  TRUCK: 'truck',
  TVMONITOR: 'tvmonitor',
  UMBRELLA: 'umbrella',
  VASE: 'vase',
  WINE_GLASS: 'wine glass',
  ZEBRA: 'zebra',
} as const;

export type YoloClassLabels = typeof _YoloClassLabels;
type YoloClassKey = keyof typeof _YoloClassLabels;
export type YoloClassLabel = (typeof _YoloClassLabels)[YoloClassKey];
