import { Admin } from "./Admin";
import { Alert } from "./Alert";
import { AlertHistory } from "./AlertHistory";
import { AssetConfig } from "./AssetConfig";
import { AssetMilestone } from "./AssetMilestone";
import { AssetOperabilitySummary } from "./AssetOperabilitySummary";
import { AssetRestrictionTable } from "./AssetRestrictionTable";
import { AssetStaff } from "./AssetStaff";
import { AssetState } from "./AssetState";
import { AssetStateChange } from "./AssetStateChange";
import { AssetStatusDetails } from "./AssetStatusDetails";
import { AssetTemplate } from "./AssetTemplate";
import { AssetWizardType } from "./AssetWizardType";
import { Credential } from "./Credential";
import { Customer } from "./Customer";
import { Dataset } from "./Dataset";
import { EdgeAgent } from "./EdgeAgent";
import { Event } from "./Event";
import { EventGroup } from "./EventGroup";
import { EventSummary } from "./EventSummary";
import { EventSummaryForAsset } from "./EventSummaryForAsset";
import { EventTrigger } from "./EventTrigger";
import { FileMetadata } from "./FileMetadata";
import { HealthcheckEvent } from "./HealthcheckEvent";
import { Log } from "./Log";
import { Manager } from "./Manager";
import { Project } from "./Project";
import { RateLimit } from "./RateLimit";
import { ResponseProtocol } from "./ResponseProtocol";
import { Sensor } from "./Sensor";
import { SensorUptime } from "./SensorUptime";
import { SensorUptimeCollector } from "./SensorUptimeCollector";
import { Summary } from "./Summary";

export type Asset = {
  type: string;
  name?: string;
  icon?: string;
  description?: string;
  referenceId?: string;
  uri?: string;
  path?: string[];
  requested?: Date;
  settingsType?: string;
  healthcheckEventsEnabled?: boolean;
  currentHealthStatus?: "ONLINE" | "OFFLINE" | "OUTDATED" | "UNKNOWN";
  currentHealthStatusDetails?: AssetCurrentStatusDetails;
  tags?: string[];
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  assetId?: string;
  _config?: AssetConfig;
  currentStateId?: string;
  templateId?: string;
  assetWizardTypeId?: string;
  customerId?: string;
  projectId?: string;
  _rateLimit?: RateLimit;
  responseProtocolId?: string;
  admins?: Admin[];
  alertHistory?: AlertHistory[];
  alerts?: Alert[];
  asset?: Asset;
  assetStates?: AssetState[];
  assetWizardType?: AssetWizardType;
  assets?: Asset[];
  config?: AssetConfig[];
  container?: AssetStorageContainer;
  credentials?: Credential[];
  currentState?: AssetState;
  customer?: Customer;
  datasets?: Dataset[];
  edgeAgents?: EdgeAgent[];
  eventGroups?: EventGroup[];
  eventSummaries?: EventSummary[];
  eventSummaryForAssets?: EventSummaryForAsset[];
  eventTriggers?: EventTrigger[];
  events?: Event[];
  healthcheckEvents?: HealthcheckEvent[];
  managers?: Manager[];
  milestone?: AssetMilestone;
  nextState?: AssetStateChange;
  operabilitySummaries?: AssetOperabilitySummary[];
  project?: Project;
  rateLimit?: RateLimit[];
  responseProtocol?: ResponseProtocol;
  restrictionTable?: AssetRestrictionTable;
  sensorUptimeCollectors?: SensorUptimeCollector[];
  sensorUptimes?: SensorUptime[];
  sensors?: Sensor[];
  staffs?: AssetStaff[];
  summaries?: Summary[];
  template?: AssetTemplate;
  trackingLogs?: Log[];
};

export type AssetCurrentStatusDetails = {
  nextCheck?: Date;
  lastNotification?: Date;
  requested?: AssetStatusDetails;
  referenceImage?: AssetStatusDetails;
  healthcheckSensors?: any[];
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  trackingLogs?: Log[];
};

export type AssetStorageContainer = {
  id?: string;
  resources?: any;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  assetId?: string;
  _picture?: FileMetadata;
  _background?: FileMetadata;
  _layout?: FileMetadata;
  _files?: FileMetadata[];
  asset?: Asset;
  background?: FileMetadata[];
  files?: FileMetadata[];
  layout?: FileMetadata[];
  picture?: FileMetadata[];
  trackingLogs?: Log[];
};
