import { Admin } from "./Admin";
import { AssetConfig } from "./AssetConfig";
import { AssetStateTemplate } from "./AssetStateTemplate";
import { AssetWizardType } from "./AssetWizardType";
import { Customer } from "./Customer";
import { EventGroupTemplate } from "./EventGroupTemplate";
import { EventTriggerTemplate } from "./EventTriggerTemplate";
import { FileMetadata } from "./FileMetadata";
import { Log } from "./Log";
import { Manager } from "./Manager";
import { Project } from "./Project";
import { SensorTemplate } from "./SensorTemplate";

export type AssetTemplate = {
  type: string;
  name?: string;
  icon?: string;
  description?: string;
  uri?: string;
  settingsType?: string;
  tags?: string[];
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  assetTemplateId?: string;
  _config?: AssetConfig;
  defaultStateId?: string;
  assetWizardTypeId?: string;
  customerId?: string;
  projectId?: string;
  assetStateTemplates?: AssetStateTemplate[];
  assetTemplate?: AssetTemplate;
  assetTemplates?: AssetTemplate[];
  assetWizardType?: AssetWizardType;
  config?: AssetConfig[];
  container?: AssetTemplateStorageContainer;
  customer?: Customer;
  defaultResponsibleAdmins?: Admin[];
  defaultResponsibleManagers?: Manager[];
  defaultState?: AssetStateTemplate;
  eventGroupTemplates?: EventGroupTemplate[];
  eventTriggerTemplates?: EventTriggerTemplate[];
  project?: Project;
  sensorTemplates?: SensorTemplate[];
  trackingLogs?: Log[];
};

export type AssetTemplateStorageContainer = {
  id?: string;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  assetTemplateId?: string;
  _picture?: FileMetadata;
  _background?: FileMetadata;
  _files?: FileMetadata[];
  assetTemplate?: AssetTemplate;
  background?: FileMetadata[];
  files?: FileMetadata[];
  picture?: FileMetadata[];
  trackingLogs?: Log[];
};
