import { ApiKey } from './ApiKey';
import { Asset } from './Asset';
import { AssetStateChange } from './AssetStateChange';
import { AssetTag } from './AssetTag';
import { AssetTemplate } from './AssetTemplate';
import { Country } from './Country';
import { Credential } from './Credential';
import { CustomerRestrictionTable } from './CustomerRestrictionTable';
import { DefaultEventComment } from './DefaultEventComment';
import { Device } from './Device';
import { DeviceEventType } from './DeviceEventType';
import { EdgeAgent } from './EdgeAgent';
import { EmergencyContact } from './EmergencyContact';
import { EventState } from './EventState';
import { Log } from './Log';
import { Manager } from './Manager';
import { Project } from './Project';
import { SensorUptime } from './SensorUptime';
import { SensorUptimeCollector } from './SensorUptimeCollector';
import { Storyline } from './Storyline';
import { StorylineCategory } from './StorylineCategory';
import { TelegramChat } from './TelegramChat';
import { TimeZone } from './TimeZone';
import { Toolkit } from './Toolkit';
import { Var } from './Var';
import { YoloClass } from './YoloClass';

export type Customer = {
  name: string;
  businessName?: string;
  description?: string;
  address?: string;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  countryId?: string;
  _config?: CustomerConfig;
  timeZoneId?: string;
  toolkitIds?: string[];
  varId?: string;
  assetTags?: AssetTag[];
  assets?: Asset[];
  assetTemplates?: AssetTemplate[];
  credentials?: Credential[];
  apiKeys?: ApiKey[];
  country?: Country;
  assetStateChanges?: AssetStateChange[];
  restrictionTable?: CustomerRestrictionTable;
  container?: CustomerStorageContainer;
  defaultEventComments?: DefaultEventComment[];
  devices?: Device[];
  deviceEventTypes?: DeviceEventType[];
  edgeAgents?: EdgeAgent[];
  emergencyContacts?: EmergencyContact[];
  eventStates?: EventState[];
  trackingLogs?: Log[];
  managers?: Manager[];
  projects?: Project[];
  sensorUptime?: SensorUptime[];
  sensorUptimeCollector?: SensorUptimeCollector[];
  storylines?: Storyline[];
  storylineCategories?: StorylineCategory[];
  telegramChats?: TelegramChat[];
  timeZone?: TimeZone;
  toolkits?: Toolkit[];
  var?: Var;
  yoloClasses?: YoloClass[];
};

export type CustomerConfig = {
  id?: string;
  dataTTL?: number;
  created?: Date;
  modified?: Date;
  deleted?: Date;
};

export type CustomerStorageContainer = {
  id?: string;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  customerId?: string;
  _logo?: File;
};
