import { Asset } from "./Asset";
import { Event } from "./Event";
import { EventSummaryForAsset } from "./EventSummaryForAsset";
import { EventTrigger } from "./EventTrigger";
import { Log } from "./Log";
import { BasedOnRulesEventSummary } from "./eventTypes/BasedOnRulesEventSummary";
import { BlacklistSearchEventSummary } from "./eventTypes/BlacklistSearchEventSummary";

export type EventSummary = {
  0?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  1?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  2?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  3?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  4?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  5?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  6?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  7?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  8?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  9?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  10?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  11?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  12?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  13?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  14?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  15?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  16?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  17?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  18?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  19?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  20?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  21?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  22?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  23?: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  type: string;
  date: Date;
  from?: Date;
  to?: Date;
  year: number;
  month: number;
  day: number;
  detail: BasedOnRulesEventSummary | BlacklistSearchEventSummary;
  updated: boolean;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  assetId?: string;
  eventSummaryForAssetId?: string;
  eventTriggerId?: string;
  asset?: Asset;
  events?: Event[];
  eventSummaryForAsset?: EventSummaryForAsset;
  eventTrigger?: EventTrigger;
  trackingLogs?: Log[];
};
