import { Asset } from "./Asset";
import { AssetState } from "./AssetState";
import { EmergencyContact } from "./EmergencyContact";
import { Event } from "./Event";
import { EventDashboard } from "./EventDashboard";
import { EventGroup } from "./EventGroup";
import { EventSubject } from "./EventSubject";
import { EventSummary } from "./EventSummary";
import { EventTriggerAssetState } from "./EventTriggerAssetState";
import { EventTriggerRule } from "./EventTriggerRule";
import { EventTriggerTemplate } from "./EventTriggerTemplate";
import { Log } from "./Log";
import { TelegramChat } from "./TelegramChat";

export type EventTrigger = {
  type: string;
  name: string;
  description?: string;
  customerId?: string;
  projectId?: string;
  subject?: string;
  enabled: boolean;
  eventGroupingByMinutes: number;
  muted: boolean;
  hidden: boolean;
  starred: boolean;
  notifications?: any;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  subjectTypeId?: string;
  assetId?: string;
  eventGroupId?: string;
  templateId?: string;
  _rules?: EventTriggerRule[];
  asset?: Asset;
  assetStates?: AssetState[];
  emergencyContacts?: EmergencyContact[];
  eventDashboards?: EventDashboard[];
  eventGroup?: EventGroup;
  events?: Event[];
  rules?: EventTriggerRule[];
  states?: EventTriggerAssetState[];
  subjectType?: EventSubject;
  summaries?: EventSummary[];
  telegramChats?: TelegramChat[];
  template?: EventTriggerTemplate;
  trackingLogs?: Log[];
};
