import { Asset } from "./Asset";
import { CctvDashboard } from "./CctvDashboard";
import { CommonAccessToken } from "./CommonAccessToken";
import { CountReport } from "./CountReport";
import { Country } from "./Country";
import { Credential } from "./Credential";
import { Customer } from "./Customer";
import { EventDashboard } from "./EventDashboard";
import { FileMetadata } from "./FileMetadata";
import { Log } from "./Log";
import { PeopleCounterReport } from "./PeopleCounterReport";
import { Report } from "./Report";
import { StoreVideoAnalyticDashboard } from "./StoreVideoAnalyticDashboard";
import { TimeZone } from "./TimeZone";
import { TrafficFlowAnalysis } from "./TrafficFlowAnalysis";
import { View } from "./View";

export type Manager = {
  name: string;
  surname?: string;
  phone?: string;
  address?: string;
  birthday?: Date;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  otpEnabled?: boolean;
  disabledPasswordLogin?: boolean;
  username?: string;
  email: string;
  emailVerified?: boolean;
  id?: string;
  customerId?: string;
  countryId?: string;
  timeZoneId?: string;
  accessTokens?: CommonAccessToken[];
  activityLogs?: Log[];
  assets?: Asset[];
  cctvDashboards?: CctvDashboard[];
  container?: ManagerStorageContainer;
  countReports?: CountReport[];
  country?: Country;
  credentials?: Credential[];
  customer?: Customer;
  eventDashboards?: EventDashboard[];
  peopleCounterReports?: PeopleCounterReport[];
  permission?: Permission;
  reports?: Report[];
  storeVideoAnalyticDashboards?: StoreVideoAnalyticDashboard[];
  timeZone?: TimeZone;
  trackingLogs?: Log[];
  trafficFlowAnalysis?: TrafficFlowAnalysis[];
  views?: View[];
};

export type ManagerStorageContainer = {
  id?: string;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  managerId?: string;
  _profile?: FileMetadata;
  manager?: Manager;
  profile?: FileMetadata[];
  trackingLogs?: Log[];
};

export type Permission = {
  master?: boolean;
  alerts?: CRUD;
  apiKeys?: CRUD;
  assets?: CRUD;
  assetStaffs?: CRUD;
  assetStates?: CRUD;
  biPanels?: CRUD;
  countReports?: CRUD;
  cctvDashboards?: CRUD;
  credentials?: CRUD;
  dashboards?: CRUD;
  defaultEventComments?: CRUD;
  devices?: CRUD;
  deviceEvents?: CRUD;
  edgeAgents?: CRUD;
  embeddedReports?: CRUD;
  emergencyContacts?: CRUD;
  events?: CRUD;
  eventGroups?: CRUD;
  eventDashboards?: CRUD;
  eventComments?: CRUD;
  eventStates?: CRUD;
  eventSubjects?: CRUD;
  eventTriggers?: CRUD;
  healthcheckEvents?: CRUD;
  faceDatabases?: CRUD;
  gis?: CRUD;
  managers?: CRUD;
  peopleCounterReports?: CRUD;
  projects?: CRUD;
  processLayouts?: CRUD;
  rekognitions?: CRUD;
  reports?: CRUD;
  sensors?: CRUD;
  storeVideoAnalyticDashboards?: CRUD;
  storylineCategories?: CRUD;
  storylines?: CRUD;
  telegramChats?: CRUD;
  trafficFlowAnalysis?: CRUD;
  virtualExpressions?: CRUD;
  listedLicensePlates?: CRUD;
  responseProtocols?: CRUD;
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  managerId?: string;
  trackingLogs?: Log[];
};

export type CRUD = {
  create?: boolean;
  read?: boolean;
  update?: boolean;
  delete?: boolean;
  id?: string;
};
