import { Asset } from './Asset';
import { AssetOperabilitySummary } from './AssetOperabilitySummary';
import { AssetTemplate } from './AssetTemplate';
import { BIPanel } from './BIPanel';
import { CctvDashboard } from './CctvDashboard';
import { CountReport } from './CountReport';
import { Credential } from './Credential';
import { Customer } from './Customer';
import { EmbeddedReport } from './EmbeddedReport';
import { EventDashboard } from './EventDashboard';
import { EventSummaryForProject } from './EventSummaryForProject';
import { FaceDatabase } from './FaceDatabase';
import { HealthcheckEvent } from './HealthcheckEvent';
import { Log } from './Log';
import { PeopleCounterReport } from './PeopleCounterReport';
import { ProjectOperabilitySummary } from './ProjectOperabilitySummary';
import { ProjectRestrictionTable } from './ProjectRestrictionTable';
import { ProjectTag } from './ProjectTag';
import { RateLimit } from './RateLimit';
import { Report } from './Report';
import { ResponseProtocol } from './ResponseProtocol';
import { SensorType } from './SensorType';
import { SensorUptime } from './SensorUptime';
import { SensorUptimeCollector } from './SensorUptimeCollector';
import { StoreVideoAnalyticDashboard } from './StoreVideoAnalyticDashboard';
import { Storyline } from './Storyline';
import { Tool } from './Tool';
import { Toolkit } from './Toolkit';
import { TrafficFlowAnalysis } from './TrafficFlowAnalysis';
import { VirtualExpression } from './VirtualExpression';
import { VirtualGroup } from './VirtualGroup';
import { VirtualVariable } from './VirtualVariable';
import { YoloClass } from './YoloClass';

export type Project = {
  name?: string;
  description?: string;
  logo?: string;
  sector?: string;
  keywords?: string[];
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  customerId?: string;
  tagIds?: string[];
  _rateLimit?: RateLimit;
  adminToolIds?: string[];
  toolIds?: string[];
  toolkitId?: string;
  trackingLogs?: Log[];
  customer?: Customer;
  assets?: Asset[];
  assetTemplates?: AssetTemplate[];
  countReports?: CountReport[];
  healthcheckEvents?: HealthcheckEvent[];
  credentials?: Credential[];
  cctvDashboards?: CctvDashboard[];
  eventDashboards?: EventDashboard[];
  eventSummaryForProjects?: EventSummaryForProject[];
  embeddedReports?: EmbeddedReport[];
  biPanels?: BIPanel[];
  peopleCounterReports?: PeopleCounterReport[];
  assetOperabilitySummaries?: AssetOperabilitySummary[];
  faceDatabases?: FaceDatabase[];
  operabilitySummaries?: ProjectOperabilitySummary[];
  restrictionTable?: ProjectRestrictionTable;
  tags?: ProjectTag[];
  reports?: Report[];
  responseProtocols?: ResponseProtocol[];
  allowedSensorTypes?: SensorType[];
  sensorUptime?: SensorUptime[];
  sensorUptimeCollectors?: SensorUptimeCollector[];
  storeVideoAnalyticDashboards?: StoreVideoAnalyticDashboard[];
  storylines?: Storyline[];
  adminTools?: Tool[];
  tools?: Tool[];
  toolkit?: Toolkit;
  trafficFlowAnalysis?: TrafficFlowAnalysis[];
  virtualExpressions?: VirtualExpression[];
  virtualGroups?: VirtualGroup[];
  virtualVariables?: VirtualVariable[];
  yoloClasses?: YoloClass[];
};
