import { Asset } from "./Asset";
import { AssetOperabilitySummary } from "./AssetOperabilitySummary";
import { AssetTemplate } from "./AssetTemplate";
import { BIPanel } from "./BIPanel";
import { CctvDashboard } from "./CctvDashboard";
import { CountReport } from "./CountReport";
import { Credential } from "./Credential";
import { Customer } from "./Customer";
import { EmbeddedReport } from "./EmbeddedReport";
import { Event } from "./Event";
import { EventDashboard } from "./EventDashboard";
import { EventSubject } from "./EventSubject";
import { EventSummaryForProject } from "./EventSummaryForProject";
import { FaceDatabase } from "./FaceDatabase";
import { FaceSubject } from "./FaceSubject";
import { HealthcheckEvent } from "./HealthcheckEvent";
import { Log } from "./Log";
import { PeopleCounterReport } from "./PeopleCounterReport";
import { ProjectOperabilitySummary } from "./ProjectOperabilitySummary";
import { ProjectRestrictionTable } from "./ProjectRestrictionTable";
import { ProjectTag } from "./ProjectTag";
import { RateLimit } from "./RateLimit";
import { Report } from "./Report";
import { ResponseProtocol } from "./ResponseProtocol";
import { SensorType } from "./SensorType";
import { SensorUptime } from "./SensorUptime";
import { SensorUptimeCollector } from "./SensorUptimeCollector";
import { StoreVideoAnalyticDashboard } from "./StoreVideoAnalyticDashboard";
import { Storyline } from "./Storyline";
import { Tool } from "./Tool";
import { Toolkit } from "./Toolkit";
import { TrafficFlowAnalysis } from "./TrafficFlowAnalysis";
import { VirtualExpression } from "./VirtualExpression";
import { VirtualGroup } from "./VirtualGroup";
import { VirtualVariable } from "./VirtualVariable";
import { YoloClass } from "./YoloClass";

export type Project = {
  name?: string;
  description?: string;
  logo?: string;
  sector?: string;
  keywords?: string[];
  created?: Date;
  modified?: Date;
  deleted?: Date;
  id?: string;
  customerId?: string;
  tagIds?: string[];
  _rateLimit?: RateLimit;
  adminToolIds?: string[];
  toolIds?: string[];
  toolkitId?: string;
  adminTools?: Tool[];
  allowedSensorTypes?: SensorType[];
  assetOperabilitySummaries?: AssetOperabilitySummary[];
  assetTemplates?: AssetTemplate[];
  assets?: Asset[];
  biPanels?: BIPanel[];
  cctvDashboards?: CctvDashboard[];
  countReports?: CountReport[];
  credentials?: Credential[];
  customer?: Customer;
  embeddedReports?: EmbeddedReport[];
  eventDashboards?: EventDashboard[];
  eventSubjects?: EventSubject[];
  eventSummaryForProjects?: EventSummaryForProject[];
  events?: Event[];
  faceDatabases?: FaceDatabase[];
  faceSubjects?: FaceSubject[];
  healthcheckEvents?: HealthcheckEvent[];
  operabilitySummaries?: ProjectOperabilitySummary[];
  peopleCounterReports?: PeopleCounterReport[];
  rateLimit?: RateLimit[];
  reports?: Report[];
  responseProtocols?: ResponseProtocol[];
  restrictionTable?: ProjectRestrictionTable;
  sensorUptime?: SensorUptime[];
  sensorUptimeCollectors?: SensorUptimeCollector[];
  storeVideoAnalyticDashboards?: StoreVideoAnalyticDashboard[];
  storylines?: Storyline[];
  tags?: ProjectTag[];
  toolkit?: Toolkit;
  tools?: Tool[];
  trackingLogs?: Log[];
  trafficFlowAnalysis?: TrafficFlowAnalysis[];
  virtualExpressions?: VirtualExpression[];
  virtualGroups?: VirtualGroup[];
  virtualVariables?: VirtualVariable[];
  yoloClasses?: YoloClass[];
};
